extensions:
    webkul-icecat-job-instance-import-features-edit:
        module: pim/form/common/edit-form

    webkul-icecat-job-instance-import-features-edit-main-image:
        module: pim/form/common/main-image
        parent: webkul-icecat-job-instance-import-features-edit
        targetZone: main-image
        config:
            path: bundles/icecatconnector/images/akeneo-icecat-connector-webkul.png

    webkul-icecat-job-instance-import-features-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: webkul-icecat-job-instance-import-features-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    webkul-icecat-job-instance-import-features-edit-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: webkul-icecat-job-instance-import-features-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    webkul-icecat-job-instance-import-features-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: webkul-icecat-job-instance-import-features-edit
        position: 1000

    webkul-icecat-job-instance-import-features-edit-tabs:
        module: pim/form/common/form-tabs
        parent: webkul-icecat-job-instance-import-features-edit
        targetZone: content
        position: 100

    webkul-icecat-job-instance-import-features-edit-properties:
        module: pim/job/common/edit/properties
        parent: webkul-icecat-job-instance-import-features-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: webkul_enrich.form.job_instance.tab.properties.title
            tabCode: webkul-icecat-job-instance-properties

    webkul-icecat-job-instance-import-features-edit-content:
        module: pim/job/product/edit/content
        parent:  webkul-icecat-job-instance-import-features-edit-tabs
        aclResourceId: pim_importexport_export_profile_content_edit
        targetZone: container
        position: 110
        config:
            tabTitle: webkul_enrich.form.job_instance.tab.content.title
            tabCode: pim-job-instance-content
            
    webkul-icecat-connector-configuration-tab-edit-icecat-attribute:
        module: icecatconnector/job/icecat-attribute
        parent: webkul-icecat-job-instance-import-features-edit-tabs
        targetZone: container
        position: 120
        config:
            fieldCode: configuration.icecatAttributes
            title: webkul_enrich.form.job_instance.tab.icecat_attribute.title
            tabCode: webkul_enrich.form.job_instance.tab.code
            otherGroup: other
            confirmation:
                title: webkul_enrich.confirmation.extra_mapping.remove.attribute.title
                subTitle: webkul_enrich.form.mapping.extra_mapping.attribute.remove.subtitle
                message: webkul_enrich.confirmation.extra_mapping.remove.attribute.message
                buttonText: webkul_enrich.confirmation.remove
            removeAttributeACL: pim_enrich_attributegroup_remove_attribute
            addAttributeACL: pim_enrich_attributegroup_add_attribute

    webkul-icecat-connector-configuration-tab-edit-icecat-attribute-add-attribute:
        module: icecatconnector/form/tab/extra-mapping/attribute/add-select
        parent: webkul-icecat-connector-configuration-tab-edit-icecat-attribute
        targetZone: actions
        aclResourceId: pim_enrich_attributegroup_add_attribute
        
    webkul-icecat-job-instance-import-features-edit-history:
        module: icecatconnector/job/history/class 
        parent: webkul-icecat-job-instance-import-features-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_import_profile_history
        position: 130
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: webkul_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    webkul-icecat-job-instance-import-features-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: webkul-icecat-job-instance-import-features-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: webkul_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    webkul-icecat-job-instance-import-features-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: webkul-icecat-job-instance-import-features-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: webkul_enrich.form.job_instance.tab.properties.label.title

    webkul-icecat-job-instance-import-features-edit-content-structure:
        module: pim/job/product/edit/content/structure
        parent: webkul-icecat-job-instance-import-features-edit-content
        targetZone: structure-filters
        position: 100
    
    webkul-icecat-job-instance-import-features-edit-content-structure-scope:
        module: pim/job/product/edit/content/structure/scope
        parent: webkul-icecat-job-instance-import-features-edit-content-structure
        targetZone: filters
        position: 90

    webkul-icecat-job-instance-import-features-edit-content-structure-locales:
        module: icecatconnector/form/common/locales
        parent: webkul-icecat-job-instance-import-features-edit-content-structure
        targetZone: filters
        position: 100
        config:
            multiple: true
            label: webkul_enrich.form.job_instance.tab.content.locales.title
            tooltip: webkul_enrich.form.job_instance.tab.content.locales.help

    webkul-icecat-job-instance-import-features-edit-label:
        module: pim/job/common/edit/label
        parent: webkul-icecat-job-instance-import-features-edit
        targetZone: title
        position: 100

    webkul-icecat-job-instance-import-features-edit-meta:
        module: pim/job/common/edit/meta
        parent: webkul-icecat-job-instance-import-features-edit
        targetZone: meta
        position: 100

    webkul-icecat-job-instance-import-features-edit-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: webkul-icecat-job-instance-import-features-edit
        targetZone: buttons
        position: 50

    webkul-icecat-job-instance-import-features-edit-delete:
        module: pim/job/import/edit/delete
        parent: webkul-icecat-job-instance-import-features-edit-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_importexport_import_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.import_profile
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_import_profile_index

    webkul-icecat-job-instance-import-features-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: webkul-icecat-job-instance-import-features-edit
        targetZone: buttons
        position: 120

    webkul-icecat-job-instance-import-features-edit-save:
        module: pim/job-instance-import-edit-form/save
        parent: webkul-icecat-job-instance-import-features-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_import_profile_show

    webkul-icecat-job-instance-import-features-edit-state:
        module: pim/form/common/state
        parent: webkul-icecat-job-instance-import-features-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    webkul-icecat-job-instance-import-features-edit-validation:
        module: pim/job/common/edit/validation
        parent: webkul-icecat-job-instance-import-features-edit
