extensions:
    webkul-icecat-job-instance-enrich-product-show:
        module: pim/form/common/edit-form

    webkul-icecat-job-instance-enrich-product-show-main-image:
        module: pim/form/common/main-image
        parent: webkul-icecat-job-instance-enrich-product-show
        targetZone: main-image
        config:
            path: bundles/icecatconnector/images/akeneo-icecat-connector-webkul.png

    webkul-icecat-job-instance-enrich-product-show-user-navigation:
        module: pim/menu/user-navigation
        parent: webkul-icecat-job-instance-enrich-product-show
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    webkul-icecat-job-instance-enrich-product-show-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: webkul-icecat-job-instance-enrich-product-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    webkul-icecat-job-instance-enrich-product-show-launch:
        module: pim/job/common/edit/launch
        parent: webkul-icecat-job-instance-enrich-product-show
        targetZone: meta
        position: 110
        config:
            label: webkul_enrich.form.job_instance.button.import.launch
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code

    webkul-icecat-job-instance-enrich-product-show-label:
        module: pim/job/common/edit/label
        parent: webkul-icecat-job-instance-enrich-product-show
        targetZone: title
        position: 100

    webkul-icecat-job-instance-enrich-product-show-edit:
        module: pim/common/redirect
        parent: webkul-icecat-job-instance-enrich-product-show
        targetZone: buttons
        position: 100
        config:
            label: webkul_enrich.form.job_instance.button.edit.title
            route: pim_importexport_import_profile_edit
            buttonClass: AknButton AknButton--action
            identifier:
                path: code
                name: code

    webkul-icecat-job-instance-enrich-product-show-subsection:
        module: pim/form/common/subsection
        parent: webkul-icecat-job-instance-enrich-product-show
        targetZone: content
        config:
            title: webkul_enrich.form.job_instance.subsection.last_executions

    webkul-icecat-job-instance-enrich-product-show-grid:
        module: pim/job/common/grid
        parent: webkul-icecat-job-instance-enrich-product-show-subsection
        position: 1000
        targetZone: content
        config:
            alias: last-import-executions-grid
            metadata:
                jobType: import