from src import akeneo

ATTR_GROUP_FAULTY = "faulty"


t = akeneo.AttributeType
TYPES_NUMERICAL = [t.DATE, t.METRIC, t.NUMBER, t.PRICE]
TYPES_CATEGORICAL = [t.BOOL, t.SELECT_SINGLE, t.REFERENCE_SINGLE]
TYPES_MULTI = [t.SELECT_MULTI, t.REFERENCE_MULTI]
TYPES_TEXT = [t.TEXT]
TYPES_TEXTAREA = [t.TEXTAREA]
