services:
    icecat_connector.repository.config:
        class: 'Webkul\IcecatConnectorBundle\Repository\IcecatMappingRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Webkul\IcecatConnectorBundle\Entity\IcecatMapping'

    icecat_connector.repository.data_mapping:
        class: 'Webkul\IcecatConnectorBundle\Repository\IcecatDataMappingRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Webkul\IcecatConnectorBundle\Entity\IcecatDataMapping'

    icecat_connector.repository.data_mapping.search:
        class: 'Webkul\IcecatConnectorBundle\Repository\IcecatDataMappingSearchableRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Webkul\IcecatConnectorBundle\Entity\IcecatDataMapping'

