<?php

namespace Webkul\IcecatConnectorBundle\Repository;

use Doctrine\ORM\EntityManager;

/**
 * IcecatDataMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcecatDataMappingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param EntityManager $em
     *
     * @param string $class
     */
    public function __construct(EntityManager $em, string $class)
    {
        parent::__construct($em, $em->getClassMetadata($class));
    }
}
