services:
    Webkul\IcecatConnectorBundle\Command\IcecatInstallCommand:
        tags:
            - { name: console.command }

    Webkul\IcecatConnectorBundle\Command\MeasurementInstallationCommand:
        arguments: 
            - '@event_dispatcher'
        tags:
            - { name: console.command }