parameters:
    webkul_icecat_connector.job.job_parameters.features.mapping.class: Webkul\IcecatConnectorBundle\JobParameters\FeaturesMappingImport
    webkul_icecat_connector.job.job_parameters.features.class: Webkul\IcecatConnectorBundle\JobParameters\FeaturesImport
    webkul_icecat_connector.job.job_parameters.enrich_product.class: Webkul\IcecatConnectorBundle\JobParameters\EnrichProduct
services:
    webkul_icecat_connector.job.job_parameters.features_mapping_import:
        class: '%webkul_icecat_connector.job.job_parameters.features.mapping.class%'
        arguments:
            - ['webkul_icecat_import_features_mapping']
            - '@pim_catalog.repository.channel'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    webkul_icecat_connector.job.job_parameters.provider.features_mapping_import:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                webkul_icecat_import_features_mapping: webkul-icecat-job-instance-import-features-mapping
        tags:
            - { name: pim_enrich.provider.form }
    
    webkul_icecat_connector.job.job_parameters.features_import:
        class: '%webkul_icecat_connector.job.job_parameters.features.class%'
        arguments:
            - ['webkul_icecat_import_features']
            - '@pim_catalog.repository.channel'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    webkul_icecat_connector.job.job_parameters.provider.features_import:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                webkul_icecat_import_features: webkul-icecat-job-instance-import-features
        tags:
            - { name: pim_enrich.provider.form }
    
    webkul_icecat_connector.job.job_parameters.enrich_product:
        class: '%webkul_icecat_connector.job.job_parameters.enrich_product.class%'
        arguments:
            - ['webkul_icecat_enrich_products']
            - '@pim_catalog.repository.channel'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    webkul_icecat_connector.job.job_parameters.provider.enrich_product:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                webkul_icecat_enrich_products: webkul-icecat-job-instance-enrich-product
        tags:
            - { name: pim_enrich.provider.form }